{% set name = "fastStructure" %}
{% set version = "1.0" %}
{% set sha256 = "f1bfb24bb5ecd108bc3a90145fad232012165c1e60608003f1c87d200f867b81" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/rajanil/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: py3.patch

build:
  number: 6
  run_exports:
    - {{ pin_subpackage('faststructure', max_pin="x") }}
  script: |
    # Build vars
    cd vars
    python setup.py build_ext --inplace
    cd ..

    # Build main
    python setup.py build_ext --inplace
    cp vars/*.so ./

    # Add shebang lines
    sed -i '1i#!/usr/bin/env python3' structure.py
    sed -i '1i#!/usr/bin/env python3' distruct.py
    sed -i '1i#!/usr/bin/env python3' chooseK.py

    # Make scripts executable
    chmod +x structure.py
    chmod +x distruct.py
    chmod +x chooseK.py

    # Install files
    mkdir -p ${PREFIX}/bin/vars
    install -v -m 755 *.py ${PREFIX}/bin
    install -v -m 755 *.so ${PREFIX}/bin
    install -v -m 755 vars/*.py ${PREFIX}/bin/vars
    install -v -m 755 vars/*.so ${PREFIX}/bin/vars

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python =3.11
    - numpy =2.3.0
    - scipy =1.15.2
    - cython =3.1.2
    - gsl =2.8
    - liblapack =3.9.0
  run:
    - python
    - numpy
    - scipy
    - gsl
    - liblapack
    - matplotlib-base

test:
  commands:
    - structure.py | grep "Usage" > /dev/null
    - distruct.py | grep "Usage" > /dev/null
    - chooseK.py | grep "Usage" > /dev/null

about:
  home: https://github.com/rajanil/fastStructure
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A variational framework for inferring population structure from SNP genotype data. Ported to python3 by @StuntsPT based on the work of @jashapiro"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - StuntsPT
