package:
  name: aliview
  version: "1.30"

source:
  git_url: https://github.com/AliView/AliView.git
  # git_tag: 1.30 - Still under construction 
  git_depth: 1

build:
  run_exports:
    - {{ pin_subpackage('aliview', max_pin=None) }}
  noarch: generic
  number: 0
  script: |
    mvn clean compile install package -DskipTests
    mkdir -p $PREFIX/share/aliview
    cp target/aliview.jar $PREFIX/share/aliview/
    mkdir -p $PREFIX/bin
    echo -e "#!/bin/bash\njava -jar $PREFIX/share/aliview/aliview.jar \"\$@\"" > $PREFIX/bin/aliview
    chmod +x $PREFIX/bin/aliview

requirements:
  build:
    - openjdk >=8
    - maven
  run:
    - openjdk >=8

about:
  home: https://ormbunkar.se/aliview/
  summary: "AliView is an intuitive and fast alignment viewer and editor for DNA and amino acid sequences."
  license: GPL-3.0

